stages:
  - build
  - package
  - deploy

gradle:
  stage: build
  image: amazoncorretto:17
  only:
    - main
  before_script:
    - chmod +x ./gradlew
  script:
    - ./gradlew clean build -x test
    - mkdir target
    - cp build/libs/$(ls build/libs | grep SNAPSHOT.jar) ${CI_PROJECT_DIR}/service.jar
  artifacts:
    paths:
      - service.jar

docker:
  stage: package
  script:
    - ls -al .
    - TARGET="tax-accounting:$(TZ="Asia/Seoul" date "+%y.%m.%d")"
    - docker build --build-arg ARCHIVE_FILE=service.jar -t $TARGET .
