variables:
  REPOSITORY_HOST: 526459572421.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

stages:
  - build
  - package
  - deploy

gradle:
  stage: build
  image: amazoncorretto:17
  only:
    - main
  before_script:
    - chmod +x ./gradlew
  script:
    - ./gradlew clean build -x test
    - mkdir target
    - cp build/libs/$(ls build/libs | grep SNAPSHOT.jar) ${CI_PROJECT_DIR}/service.jar
  artifacts:
    paths:
      - service.jar

docker:
  stage: package
  script:
    - ls -al .
    - TARGET="tax-accounting:$(TZ="Asia/Seoul" date "+%y.%m.%d")"
    - docker build --build-arg ARCHIVE_FILE=service.jar -t ${TARGET} .
    - docker tag ${TARGET} ${REPOSITORY_HOST}/dv-service.${TARGET}

aws:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  before_script:
    - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
    - aws configure set aws_secret_key ${AWS_SECRET_ACCESS_KEY}
    - aws configure set default.region ${AWS_DEFAULT_REGION}
    - sts=($(
      aws sts assume-role \
      --role-arn "arn:aws:iam::526459572421:role/role-supervisor-access" \
      --role-session-name "ecr-work-session" \
      --query Credentials.[AccessKeyId,SecretAccessKey,SessionToken] \
      --output text
      ))
    - export AWS_ACCESS_KEY_ID=${sts[0]}
    - export AWS_SECRET_ACCESS_KEY=${sts[1]}
    - export AWS_SESSION_TOKEN=${sts[2]}
    - docker images
    - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${REPOSITORY_HOST}
  script:
    - docker push ${REPOSITORY_HOST}/dv-service.${TARGET}
