variables:
  REPOSITORY_HOST: 526459572421.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
  APP_NAME: tax-accounting

stages:
  - build
  - package
  - deploy

gradle:
  stage: build
  image: amazoncorretto:17
  only:
    - main
  before_script:
    - chmod +x ./gradlew
  script:
    - ./gradlew clean build -x test
    - mkdir target
    - cp build/libs/$(ls build/libs | grep SNAPSHOT.jar) ${CI_PROJECT_DIR}/service.jar
  artifacts:
    paths:
      - service.jar

docker:
  stage: package
  script:
    - ls -al .
    - docker build --build-arg ARCHIVE_FILE=service.jar -t ${APP_NAME}:latest .

aws:
  stage: deploy
#  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  image:
    name: amazon/aws-cli:latest
    entrypoint: ["/bin/sh", "-c"]
  before_script:
    - eval "$(curl "https://s3.ap-northeast-2.amazonaws.com/sugarbricks.static/scripts/assume-role.sh")"
    - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${REPOSITORY_HOST}
  script:
    - DEPLOY_IMAGE="${REPOSITORY_HOST}/dv-service.${APP_NAME}:$(TZ="Asia/Seoul" date "+%y.%m.%d")"
    - docker tag ${APP_NAME}:latest ${DEPLOY_IMAGE}
    - docker push ${DEPLOY_IMAGE}
