stages:
  - build
  - deploy

build:
  stage: build
  only:
    - main
  before_script:
    - echo "============================================"
    - echo " Dr.village - build tax-accounting-service"
    - echo "============================================"
    - chmod +x ./gradlew
  script:
    - ./gradlew clean build -x test
