stages:
  - compile
  - build
  - deploy

gradle:
  stage: compile
  image: amazoncorretto:17
  only:
    - main
  before_script:
    - chmod +x ./gradlew
  script:
    - ./gradlew clean build -x test
    - ls -al build/libs

docker:
  stage: build
  image: docker:latest
  script:
    - ARCHIVE="build/libs/$(ls build/libs | grep SNAPSHOT.jar)"
    - TARGET="tax-accounting:$(date "+%Y.%m.%d")"
    - docker build --build-arg ARCHIVE_FILE=$ARCHIVE -t $TARGET .
