spring:
  application:
    name: tax-accounting

  config:
    import: "configserver:"
  cloud:
    config:
      failFast: true
      retry:
        initialInterval: 3000
        multiplier: 1.3
        maxInterval: 10000
        maxAttempts: 20
      uri: http://config-server
      label: v1