GET {{host}}/v1/purchase/confirmations/types
Accept: application/json

### 사용자 비용 분개 목록 조회
GET {{host}}/v1/purchase/journal-entry/cid01
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3NlY3VyZS5kb2N0b3J2aWxsYWdlLm5ldCIsInN1YiI6ImU5MTc3ZTc1LWQwYmQtMzE0OC04NGIxLWIwYzdhZmUzZmM1Ny11LmR2Lm5ldCIsImF1ZCI6Imh0dHBzOi8vd3d3LmRvY2ppYi5uZXQiLCJpYXQiOjE2OTE5NzUyMjksImV4cCI6MTY5MjIzNDQyOSwiYWNjZXNzX3Rva2VuIjoiNGRmMzY1ODZiY2UzNjZiMzhhMTg0YzY0YzQwOTBjMTM4NTAwZTFmMmVlYmQ4YTYxMWVmZGNmYmI3ZjE3ZDYwYSIsIm5hbWUiOiLsnqXsoJXtlYQiLCJlbWFpbCI6Imp1cGhpY2hAc3VnYXJicmlja3MuY28ua3IiLCJyb2xlcyI6W10sImdyb3VwIjp7ImlkIjoiIiwibmFtZSI6IiIsInR5cGUiOiIifX0.YnK0YdkVAkIGSPZd8IurF6qp_YyW_AN6lwn1rO9vx0o


### 계정 분계 상세 정보 조회
#    CREDIT_CARD("CC", "신용카드"),
#    CASH_RECEIPT("CR", "현금영수증"),
#    TAX_INVOICE("TI", "전자세금계산서"),
#    INVOICE("II", "전자계산서"),
#    HANDWRITTEN_INVOICE("HI", "수기세금계산서"),
#    BASIC_RECEIPT("BR", "간이영수증"),;
GET {{host}}/v1/purchase/journal-entry/CREDIT_CARD/4509
Accept: application/json


### 계정분계처리 요청
POST {{host}}/v1/purchase/journal-entry/CREDIT_CARD/33330
Content-Type: application/json

{
  "note": "근처 백화점에서 사무용품 구매했음. 수정",
  "checkExpense": true,
  "requester": "requester-id"
}


### 계정분계요청 처리
PUT {{host}}/v1/purchase/journal-entry/CREDIT_CARD/33330
Content-Type: application/json

{
  "note": "병원장님과 유선상으로 재확인 하여 계정과면 분개함",
  "accountingItem": "342",
  "committer": "committer-id"
}

### 계정과목 분계 처리 내역
GET {{host}}/v1/purchase/journal-entry/credit_card/33330/history
Accept: application/json

### 비용처리 현황 내역, 신용카드
GET {{host}}/v1/purchase/journal-entry/cid01/credit_card/state?page=1&pageSize=10&sort[]=id,desc&sort[]=name,asc&sort[]=createdAt,desc
Accept: application/json

### 비용처리 현황 내역, 현금영수증
GET {{host}}/v1/purchase/journal-entry/cid01/cash_receipt/state
Accept: application/json

### 비용처리 현황 내역, 전자세금 계산서
GET {{host}}/v1/purchase/journal-entry/cid01/tax_invoice/state
Accept: application/json
